title: Jakub Vítovec
email: jakvitov@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website, where I as a software developer post various of my personal 
  projects or just share some random thoughts and code snippets. 
baseurl: ""
url: https://jakvitov.cz
github_username: jakvitov
linkedin_username: jakub-vítovec-91a838232

# Build settings
theme: minima
plugins:
  - jekyll-feed

source: .
destination: ./_site

defaults:
 -
   scope:
     path: "posts"
   values:
     layout: "post"
     author: "Jakub Vítovec"

collections:
  projects:
    output: true
    permalink: /projects/:title/

